# Generated by Django 2.0.5 on 2018-05-29 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacaoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacaoes',
            options={'verbose_name_plural': 'Transacoes'},
        ),
        migrations.AlterField(
            model_name='transacaoes',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.Categoria'),
        ),
        migrations.AlterField(
            model_name='transacaoes',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transacaoes',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
